name: build

on:

  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: RELEASE=1 WERROR=1 make pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ddb_signals
        if-no-files-found: error
        path: build/release/pkg/ddb_signals-*.tar.gz
